require 'rake/clean'

LESS   = FileList['less/**/*.less']
COFFEE = FileList['coffee/**/*.coffee']

CSS  = LESS.ext('css')
JS   = COFFEE.ext('js')

CLOBBER.include(CSS, JS)

rule '.css' => '.less' do |t|
   puts "  LESS #{t.source}"
   sh "mkdir", "-p", "tmp/css"
   sh 'lessc', '-x',t.source, "tmp/css/#{t.name[5..-1]}"
end

rule '.js' => '.coffee' do |t|
   puts "COFFEE #{t.source}"
   sh 'coffee', '-o', "tmp/javascript/#{File.dirname(t.name[7..-1])}" , '-c', t.source
end

desc "Package assets"
task :after do
  sh 'jammit'
end

desc "clean"
task :clean do
  sh "rm", "-rf", "tmp"
  sh "rm", "-rf", "public/*"
end

desc "Build all HTML, CSS and JavaScript files"
task :default => (CSS + JS)

desc "Continuously watch for changes and rebuild files"
task :watch => [] do
    require 'rubygems'
    require 'fssm'

    def rebuild
        sh 'rake clean default'
        sh 'haml' , '-t', 'ugly', "index.haml", "public/index.html"
        sh "cp", "-rf", "image", "public"
        sh 'jammit'
        
        puts "    OK"
    rescue
        nil
    end

    begin
        rebuild
        FSSM.monitor(nil, ['**/*.coffee', '**/*.haml', '**/*.less']) do
            update { rebuild }
            delete { rebuild }
            create { rebuild }
        end
    rescue FSSM::CallbackError => e
        Process.exit
    end

end